FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR c:/app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR c:/src
COPY ["src/", "."]
RUN dotnet build "HelloWorldService.csproj" -c Release -o c:/app/build

FROM build AS publish
RUN dotnet publish "HelloWorldService.csproj" -c Release -o c:/app/publish

FROM base AS final
WORKDIR c:/app
COPY --from=publish c:/app/publish .
ENTRYPOINT ["dotnet", "HelloWorldService.dll"]